[theme]
primaryColor = "#137c78"
backgroundColor = "#f7f9fb"
secondaryBackgroundColor = "#edf2f6"
textColor = "#172b3a"
font = "sans serif"

[server]
address = "127.0.0.1"
headless = true

[browser]
gatherUsageStats = false
